name: Blog Deploy

on:
  push:
    branches: ["main"]
    paths: ["apps/blogs/**"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean temp directory
        run: |
          rm -rf *

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "18.x"

      - name: Build
        run: |
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js build -o @apps/blogs --verbose
          node common/scripts/install-run-rush.js deploy -p @apps/blogs

      - name: Github Pages Action
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          external_repository: sma2lbao/blog
          deploy_key: ${{ secrets.BLOG_DEPLOY_KEY }}
          publish_dir: ./apps/blogs/.next
