name: Design Core StoryBook Pipline

on:
  push:
    branches: ["main"]
    paths: ["design/design-core/**"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean temp directory
        run: |
          rm -rf *

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: |
          node common/scripts/install-run-rush.js install --bypass-policy

      - name: Build
        run: |
          node common/scripts/install-run-rush.js build-storybook -o @design/core

      - name: Github Pages Action
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          external_repository: sma2lbao/design-core
          deploy_key: ${{ secrets.DESIGN_CORE_DEPLOY_KEY }}
          publish_dir: design/design-core/dist/storybook
